import type { Tables, TablesInsert } from "./db/database.types";

/**
 * Represents the public profile of a user.
 *
 * @description This DTO corresponds to the `profiles` table and is used in the
 * `GET /api/me/profile` endpoint response.
 */
export type ProfileDto = Tables<"profiles">;

/**
 * Represents the command for updating a user's profile.
 *
 * @description This command model is used as the request payload for the
 * `PATCH /api/me/profile` endpoint. It includes only the fields that
 * can be modified by the user. All fields are optional.
 */
export type UpdateProfileCommand = Partial<
  Pick<Tables<"profiles">, "full_name" | "avatar_url" | "allergies" | "diets" | "disliked_ingredients">
>;

/**
 * Represents a recipe as it appears in a list.
 *
 * @description This DTO is a lightweight representation of a recipe, excluding
 * heavier fields like `ingredients` and `instructions`. It's used in the
 * response of the `GET /api/recipes` endpoint.
 */
export type RecipeListItemDto = Omit<Tables<"recipes">, "ingredients" | "instructions" | "changes_summary">;

/**
 * Represents the full details of a single recipe.
 *
 * @description This DTO corresponds to the `recipes` table and includes all
 * fields. It is used in the response for `GET /api/recipes/{recipeId}` and
 * `POST /api/recipes`.
 */
export type RecipeDetailDto = Tables<"recipes">;

/**
 * Represents the command for creating a new recipe.
 *
 * @description This command model is used as the request payload for the
 * `POST /api/recipes` endpoint. It contains the essential fields needed
 * to create a new recipe record.
 */
export type CreateRecipeCommand = Pick<
  TablesInsert<"recipes">,
  "title" | "ingredients" | "instructions" | "original_recipe_id"
>;

/**
 * Represents an unsaved, AI-modified recipe.
 *
 * @description This DTO is the response from the `POST /api/recipes/{recipeId}/modify`
 * endpoint. It is a complete recipe structure, but since it has not been persisted
 * to the database, `id`, `created_at`, and `updated_at` are `null`.
 */
export type ModifiedRecipeDto = Omit<Tables<"recipes">, "id" | "created_at" | "updated_at"> & {
  id: null;
  created_at: null;
  updated_at: null;
};

/**
 * Represents the local state of the ProfileForm component.
 *
 * @description This ViewModel is initialized from ProfileDto and used to manage
 * the form state in the ProfileForm component.
 */
export interface ProfileFormViewModel {
  full_name: string;
  avatar_url: string;
  allergies: string[];
  diets: string[];
  disliked_ingredients: string[];
}

/**
 * Represents an option in a select/combobox component.
 *
 * @description This utility type is used for dropdown and multi-select components
 * like MultiSelectCombobox.
 */
export interface SelectOption {
  label: string;
  value: string;
}

/**
 * Represents the paginated response from the GET /api/recipes endpoint.
 *
 * @description Contains an array of recipe list items and pagination metadata.
 */
export interface PaginatedRecipesResponse {
  data: RecipeListItemDto[];
  pagination: {
    page: number;
    pageSize: number;
    total: number;
  };
}

/**
 * Represents the query parameters for fetching recipes.
 *
 * @description Used for managing the state of pagination, sorting, and filtering
 * in the Recipe Library View.
 */
export interface GetRecipesQueryParams {
  page: number;
  pageSize: number;
  sortBy: "created_at" | "updated_at" | "title";
  order: "asc" | "desc";
}

/**
 * Represents a recipe in the Recipe Library View.
 *
 * @description This ViewModel is derived from RecipeListItemDto and includes
 * computed properties for easier rendering and UI logic.
 */
export interface RecipeViewModel {
  id: string;
  title: string;
  isOriginal: boolean;
  statusLabel: "Original" | "AI-Modified";
  displayDate: string;
  linkPath: string;
}

/**
 * Represents a recipe in the Recipe Details View.
 *
 * @description This ViewModel is derived from RecipeDetailDto and includes
 * computed properties for rendering the full recipe with AI modification indicators.
 */
export interface RecipeDetailsViewModel {
  id: string;
  title: string;
  ingredients: string;
  instructions: string;
  isAIModified: boolean;
  statusLabel: "Original" | "AI-Modified";
  changesSummary: string | null;
  isDisclaimerNeeded: boolean;
}

// ============================================================================
// AI Modification View Types
// ============================================================================

/**
 * Represents a single, structured change generated by the AI.
 *
 * @description Used in the ChangeSummaryList component to display
 * individual modifications made by the AI to the recipe.
 */
export interface AIChangeSummary {
  type: string;
  from: string;
  to: string;
}

/**
 * Combines all required data for the AI modification review components.
 *
 * @description This ViewModel orchestrates the data flow for the entire
 * AI modification flow, including the original recipe, modified version,
 * parsed changes summary, and ready-to-save payload.
 */
export interface AIModificationViewModel {
  originalRecipe: RecipeDetailDto;
  modifiedRecipe: ModifiedRecipeDto;
  originalRecipeId: string;
  changesSummary: AIChangeSummary[];
  isReadyToSave: boolean;
  savePayload: CreateRecipeCommand;
}

// ============================================================================
// OpenRouter Service Types
// ============================================================================

/**
 * Represents a single message in the chat completion API.
 *
 * @description Used for constructing the messages array in ChatCompletionRequest.
 * Supports system, user, and assistant roles.
 */
export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

/**
 * Represents the structured response format configuration.
 *
 * @description Used to enforce JSON schema validation on the model's response.
 * When provided, the model will return structured JSON output conforming to the schema.
 */
export interface ResponseFormat {
  type: "json_schema";
  json_schema: {
    name: string;
    strict: boolean;
    schema: Record<string, unknown>;
  };
}

/**
 * Represents the request payload for the OpenRouter Chat Completions API.
 *
 * @description Contains the model name, messages array, optional parameters
 * (temperature, max_tokens, top_p), and optional response format for structured output.
 */
export interface ChatCompletionRequest {
  model: string;
  messages: ChatMessage[];
  temperature?: number;
  max_tokens?: number;
  top_p?: number;
  response_format?: ResponseFormat;
}

/**
 * Represents the usage information returned by the OpenRouter API.
 *
 * @description Contains token counts for the request and response.
 */
export interface ChatCompletionUsage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
}

/**
 * Represents the response from the OpenRouter Chat Completions API.
 *
 * @description Contains the model's response message, usage information,
 * and other metadata about the completion.
 */
export interface ChatCompletionResponse {
  id: string;
  model: string;
  created: number;
  choices: {
    index: number;
    message: ChatMessage;
    finish_reason: string;
  }[];
  usage: ChatCompletionUsage;
}

// ============================================================================
// OpenRouter Service Error Classes
// ============================================================================

/**
 * Base error class for all OpenRouter service errors.
 *
 * @description Extends the native Error class and serves as the parent
 * for all specific OpenRouter error types.
 */
export class OpenRouterError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "OpenRouterError";
    Object.setPrototypeOf(this, OpenRouterError.prototype);
  }
}

/**
 * Error thrown when authentication fails (401).
 *
 * @description Indicates an invalid or missing API key.
 */
export class AuthError extends OpenRouterError {
  constructor(message = "Invalid OpenRouter API Key.") {
    super(message);
    this.name = "AuthError";
    Object.setPrototypeOf(this, AuthError.prototype);
  }
}

/**
 * Error thrown when rate limit is exceeded (429).
 *
 * @description Indicates too many requests have been made to the API.
 */
export class RateLimitError extends OpenRouterError {
  constructor(message = "Too many requests. Please try again later.") {
    super(message);
    this.name = "RateLimitError";
    Object.setPrototypeOf(this, RateLimitError.prototype);
  }
}

/**
 * Error thrown when the request payload is invalid (400).
 *
 * @description Indicates a problem with the request structure or parameters.
 */
export class BadRequestError extends OpenRouterError {
  constructor(message = "The request payload is invalid.") {
    super(message);
    this.name = "BadRequestError";
    Object.setPrototypeOf(this, BadRequestError.prototype);
  }
}

/**
 * Error thrown when the LLM provider service is unavailable (5xx).
 *
 * @description Indicates a server-side error from OpenRouter or the underlying model provider.
 */
export class ModelServiceError extends OpenRouterError {
  constructor(message = "The LLM provider service is currently unavailable.") {
    super(message);
    this.name = "ModelServiceError";
    Object.setPrototypeOf(this, ModelServiceError.prototype);
  }
}

/**
 * Error thrown when response parsing fails.
 *
 * @description Indicates the model's response could not be parsed as expected JSON.
 */
export class ParsingError extends OpenRouterError {
  constructor(message = "Model response is malformed and cannot be parsed as JSON.") {
    super(message);
    this.name = "ParsingError";
    Object.setPrototypeOf(this, ParsingError.prototype);
  }
}
